"""End-to-end smoke test for paperconan.

Builds a synthetic xlsx fixture that's designed to trip three core detectors
and asserts both the scan.json structure and that report.html is well-formed.
"""
from __future__ import annotations

import json
import os
import sys

import pytest

# Make tests/build_fixture importable when running pytest from repo root.
sys.path.insert(0, os.path.dirname(__file__))
from build_fixture import build  # noqa: E402

from paperconan import scan_dir, write_html_report  # noqa: E402


@pytest.fixture(scope="module")
def tiny_paper(tmp_path_factory):
    d = tmp_path_factory.mktemp("tiny_paper")
    build(str(d))
    return str(d)


def _collect_kinds(scan: dict) -> set[str]:
    kinds = set()
    for blk in scan.get("relations_blocks") or []:
        for group in ("relations", "progressions", "equal_pairs",
                      "within_col", "identical_after_rounding"):
            for f in blk.get(group, []) or []:
                kinds.add(f["kind"])
    for cf in scan.get("cross_sheet_findings") or []:
        kinds.add(cf["kind"])
    return kinds


def test_scan_dir_finds_expected_detectors(tiny_paper, tmp_path):
    out_dir = tmp_path / "out"
    res = scan_dir(tiny_paper, str(out_dir))

    assert (out_dir / "scan.json").exists()
    assert (out_dir / "report.html").exists(), "report.html should be the default output"
    assert not (out_dir / "REPORT.md").exists(), "REPORT.md should be opt-in via --md"

    kinds = _collect_kinds(res)
    assert "identical_column" in kinds, f"expected identical_column, got: {kinds}"
    assert "arithmetic_progression" in kinds, f"expected arithmetic_progression, got: {kinds}"
    assert "cross_sheet_position_identical" in kinds, \
        f"expected cross_sheet_position_identical, got: {kinds}"


def test_scan_carries_provenance(tiny_paper, tmp_path):
    out_dir = tmp_path / "out"
    res = scan_dir(tiny_paper, str(out_dir))
    assert res.get("tool") == "paperconan"
    assert res.get("tool_version"), "scan.json should record the paperconan version"
    # The wall-clock timestamp is opt-in (keeps default scan.json reproducible);
    # it is present only when runtime metadata is requested.
    assert res.get("scanned_at") is None
    timed = scan_dir(tiny_paper, str(tmp_path / "out_timed"), runtime_metadata=True)
    assert timed.get("scanned_at"), "runtime metadata should record a scan timestamp"

    html = (out_dir / "report.html").read_text(encoding="utf-8")
    assert "generated by paperconan" in html
    assert res["tool_version"] in html


def test_findings_carry_evidence(tiny_paper, tmp_path):
    out_dir = tmp_path / "out"
    res = scan_dir(tiny_paper, str(out_dir))

    block_findings = []
    for blk in res["relations_blocks"]:
        for group in ("relations", "progressions", "equal_pairs",
                      "within_col", "identical_after_rounding"):
            block_findings.extend(blk.get(group, []) or [])

    assert block_findings, "expected at least one block-level finding"
    for f in block_findings:
        ev = f.get("evidence")
        assert ev, f"finding {f['kind']} missing evidence"
        assert ev["rows"], f"evidence on {f['kind']} has no rows"
        assert isinstance(ev["highlight_cols"], list)
        assert ev["headers"], "evidence headers should not be empty"


def test_html_report_is_well_formed(tiny_paper, tmp_path):
    out_dir = tmp_path / "out"
    scan_dir(tiny_paper, str(out_dir))

    html_path = out_dir / "report.html"
    html = html_path.read_text(encoding="utf-8")
    assert html.startswith("<!DOCTYPE html>")
    assert "<table" in html, "expected at least one evidence table"
    assert "identical_column" in html
    assert "cross_sheet_position_identical" in html
    assert len(html) > 5000, "report seems too small to contain rendered findings"


def test_md_flag_writes_report_md(tiny_paper, tmp_path):
    out_dir = tmp_path / "out"
    scan_dir(tiny_paper, str(out_dir), write_md=True, write_html=True)
    assert (out_dir / "REPORT.md").exists()
    assert (out_dir / "report.html").exists()


def test_no_html_flag_skips_html(tiny_paper, tmp_path):
    out_dir = tmp_path / "out"
    scan_dir(tiny_paper, str(out_dir), write_md=False, write_html=False)
    assert (out_dir / "scan.json").exists()
    assert not (out_dir / "report.html").exists()


_CSV_ONE = (
    "sample,height,weight,score\n"
    "s1,1.2345,55.6789,9.1234\n"
    "s2,1.8923,60.1234,8.7654\n"
    "s3,2.5612,58.4321,9.3456\n"
    "s4,3.1456,62.7890,8.9012\n"
    "s5,3.8721,59.5678,9.5678\n"
    "s6,4.2389,61.2345,8.4321\n"
)
# Same height/weight values at the same positions as _CSV_ONE -> cross-file collision.
_CSV_TWO = (
    "id,h,w,sc\n"
    "a1,1.2345,55.6789,3.1111\n"
    "a2,1.8923,60.1234,3.2222\n"
    "a3,2.5612,58.4321,3.3333\n"
    "a4,3.1456,62.7890,3.4444\n"
    "a5,3.8721,59.5678,3.5555\n"
    "a6,4.2389,61.2345,3.6666\n"
)


def test_csv_cross_file_collision(tmp_path):
    data = tmp_path / "csv_data"
    data.mkdir()
    (data / "dataset_one.csv").write_text(_CSV_ONE, encoding="utf-8")
    (data / "dataset_two.csv").write_text(_CSV_TWO, encoding="utf-8")

    out_dir = tmp_path / "out"
    res = scan_dir(str(data), str(out_dir))

    assert res["n_files"] == 2
    collisions = [cf for cf in res["cross_sheet_findings"]
                  if cf["kind"] == "cross_sheet_position_identical"]
    assert collisions, "expected a cross-file position-identical collision"
    cf = collisions[0]
    assert cf["same_file"] is False, "collision should be flagged as cross-file"
    assert cf["file_a"] != cf["file_b"]


def test_tsv_and_text_columns_are_handled(tmp_path):
    data = tmp_path / "tsv_data"
    data.mkdir()
    # A TSV with a text column and a verbatim-duplicate numeric column.
    rows = ["label\tmass\tmass_copy\tnote"]
    for i in range(6):
        v = round(1.1 + i * 0.7, 4)
        rows.append(f"row{i}\t{v}\t{v}\tok")
    (data / "table.tsv").write_text("\n".join(rows) + "\n", encoding="utf-8")

    out_dir = tmp_path / "out"
    res = scan_dir(str(data), str(out_dir))
    assert res["n_files"] == 1
    kinds = set()
    for blk in res["relations_blocks"]:
        for f in blk.get("relations", []):
            kinds.add(f["kind"])
    assert "identical_column" in kinds, f"expected identical_column from TSV, got {kinds}"


def test_scan_reads_provenance_sidecar(tmp_path):
    """A paperconan_source.json left by `fetch` is read so scan.json records which
    paper the data belongs to."""
    data = tmp_path / "data"
    data.mkdir()
    (data / "t.csv").write_text("a,b\n1.234,5.678\n2.345,6.789\n3.456,7.890\n", encoding="utf-8")
    (data / "paperconan_source.json").write_text(
        '{"doi": "10.1038/s41590-026-02471-0", "title": "CLEC12B"}', encoding="utf-8")
    res = scan_dir(str(data), str(tmp_path / "out"), write_html=False)
    assert res["paper"]["doi"] == "10.1038/s41590-026-02471-0"
    assert res["paper"]["title"] == "CLEC12B"


def test_scan_paper_arg_overrides_sidecar(tmp_path):
    data = tmp_path / "data"
    data.mkdir()
    (data / "t.csv").write_text("a,b\n1.234,5.678\n2.345,6.789\n3.456,7.890\n", encoding="utf-8")
    (data / "paperconan_source.json").write_text('{"doi": "10.x/sidecar"}', encoding="utf-8")
    res = scan_dir(str(data), str(tmp_path / "out"), write_html=False,
                   paper={"doi": "10.x/override"})
    assert res["paper"]["doi"] == "10.x/override"


def test_scan_without_provenance_has_null_paper(tmp_path):
    data = tmp_path / "data"
    data.mkdir()
    (data / "t.csv").write_text("a,b\n1.234,5.678\n2.345,6.789\n3.456,7.890\n", encoding="utf-8")
    res = scan_dir(str(data), str(tmp_path / "out"), write_html=False)
    assert res["paper"] is None


def test_write_html_report_handles_empty_scan(tmp_path):
    out_path = tmp_path / "empty.html"
    write_html_report({
        "input_dir": "/tmp/nothing",
        "n_files": 0,
        "n_blocks_with_findings": 0,
        "relations_blocks": [],
        "digit_distribution": [],
        "decimal_endings": [],
        "cross_sheet_findings": [],
    }, str(out_path))
    html = out_path.read_text(encoding="utf-8")
    assert "no findings" in html
    assert "<!DOCTYPE html>" in html
